platform :ios, '11.0'

workspace 'shop'
inhibit_all_warnings!

target 'Service' do
    use_frameworks!
    project 'Service/Service'
    
    #msg
pod 'Moya'
pod 'SDWebImage'
   

end

target 'App' do
  use_frameworks!
  project 'App/App'
pod 'Moya'
pod 'SDWebImage'
  
end

target 'shop' do
  use_frameworks!

  #msg
pod 'Moya'
pod 'SDWebImage'
  
end





$iOSVersion = '11.0'

pre_install do |installer|
  # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

post_install do |installer|
 # add these lines:
 installer.pods_project.build_configurations.each do |config|
  config.build_settings["EXCLUDED_ARCHS[sdk=*]"] = "armv7"
  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $iOSVersion
 end
  
 installer.pods_project.targets.each do |target|
   
  # add these lines:
  target.build_configurations.each do |config|
    config.build_settings['ENABLE_BITCODE'] = 'NO'
   if Gem::Version.new($iOSVersion) > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $iOSVersion
   end
  end
   
 end
end


